version: '1.0'

services:
  nestapp:
    container_name: nestapp
    image: tung/nestapp:1.0.0
    build: .
    ports:
      - 9000:9000
    environment:
      - DB_TYPE=postgres
      - DB=postgres
      - DB_HOST=db
      - DB_USER=postgres
      - BD_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - dbpg
  dbpg:
    container_name: dbpg
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgres/data
volumes:
  pgdata: {}
